import { ArrowUpRight, Github } from 'lucide-react';

const projects = [
  { name: 'myMentor', tagline: 'AI-powered learning roadmaps and progress workspace.', description: 'A personalized learning platform for building roadmaps, tracking study progress, logging hours, and gamifying consistent practice.', tags: ['TypeScript', 'React', 'FastAPI', 'PostgreSQL', 'AI'], accent: 'rose', link: 'https://github.com/cser-utkarsh-raj/myMentor', emoji: '🧑‍🏫', features: ['Personalized roadmap generation', 'Progress tracking with XP, streaks, and achievements', 'Focused study and productivity workspace'] },
  { name: 'TerraVault', tagline: 'Knowledge CMS with revision audits and analytics.', description: 'A community-driven educational encyclopedia and custom CMS with editorial permissions, rollback-friendly revisions, and traffic monitoring.', tags: ['Flask', 'Python', 'PostgreSQL', 'SQLAlchemy', 'Docker'], accent: 'sky', link: 'https://github.com/cser-utkarsh-raj/TerraVault', emoji: '🌍', features: ['Role-based access for writers and admins', 'Article revision history and rollback support', 'Interactive page traffic metrics'] },
  { name: 'Sprintor', tagline: 'StoreBook demo for inventory and procurement workflows.', description: 'A full-stack enterprise demo for inventory tracking, low-stock warnings, and student request workflows across services.', tags: ['Java', 'Spring Boot', 'React', 'Docker', 'Jenkins'], accent: 'lime', link: 'https://github.com/cser-utkarsh-raj/Final-Project', emoji: '📦', features: ['Microservices with gateway and config services', 'Inventory deduction through inter-service workflows', 'Containerized development and CI/CD integration'] },
  { name: 'Sailor', tagline: 'Anonymous social space for spontaneous connection.', description: 'A social product for discovering real people, conversations, communities, and connections without the pressure of traditional social media.', tags: ['TypeScript', 'Social', 'Community', 'Product'], accent: 'purple', link: 'https://github.com/cser-utkarsh-raj/Sailor', emoji: '⛵', features: ['Anonymous discovery and conversations', 'Community-oriented social spaces', 'Connection-first product experience'] },
  { name: 'SLAM', tagline: 'AI-powered job discovery and application workspace.', description: 'A job-search workspace that finds relevant opportunities, explains candidate fit, tailors applications, and keeps the search organized.', tags: ['TypeScript', 'AI', 'Career Tech'], accent: 'yellow', link: 'https://github.com/cser-utkarsh-raj/SLAM', emoji: '🚀', features: ['Relevant opportunity discovery', 'Explainable fit analysis', 'Application tailoring and organization'] },
  { name: 'ClickHead', tagline: 'High-concurrency HTTP traffic simulation engine.', description: 'A realistic traffic simulation tool designed for modern infrastructure testing, avoiding unnatural spikes that can trigger WAF bot filters.', tags: ['Go', 'TypeScript', 'Performance', 'Testing'], accent: 'lime', link: 'https://github.com/cser-utkarsh-raj/ClickHead', emoji: '⚡', features: ['High-concurrency request generation', 'Realistic request distribution', 'Performance and load-testing scenarios'] },
  { name: 'NailedIt', tagline: 'Thumbnail generator for blogs, YouTube, and social media.', description: 'A creator-focused tool for making custom thumbnails with a fast, repeatable visual content workflow.', tags: ['TypeScript', 'Design Tools', 'Creators'], accent: 'rose', link: 'https://github.com/cser-utkarsh-raj/NailedIt', emoji: '🎨', features: ['Multi-platform thumbnail creation', 'Creator-friendly design workflow', 'Reusable visual content tooling'] },
  { name: 'Shennong', tagline: 'ML-powered agricultural intelligence for crop and market decisions.', description: 'The FarmHub project presented as an applied ML product for helping farmers make better crop and market decisions.', tags: ['TypeScript', 'Machine Learning', 'Agriculture', 'Data'], accent: 'sky', link: 'https://github.com/cser-utkarsh-raj/FarmHub', emoji: '🌾', features: ['Crop decision support', 'Market-focused agricultural insights', 'Applied data-driven product workflow'] },
  { name: 'Medusa', tagline: 'ML project for intelligent, data-driven workflows.', description: 'An applied machine-learning project focused on intelligent automation, inference-driven decisions, and useful data-backed experiences.', tags: ['Python', 'Machine Learning', 'AI', 'Data'], accent: 'purple', link: 'https://github.com/cser-utkarsh-raj', emoji: '🧠', features: ['Model-driven workflow and inference', 'Applied AI product thinking', 'Data-backed user experiences'] },
  { name: '.dot', tagline: 'Private project from my second GitHub profile.', description: 'A selected project from the hidden .dot repository on cser-utkarsh-raj.', tags: ['Private', 'Product', 'Development'], accent: 'yellow', link: 'https://github.com/cser-utkarsh-raj/.dot', emoji: '·', features: ['Linked to the second GitHub profile', 'Kept intentionally concise', 'Project details remain private'] },
  { name: 'The Bloom', tagline: 'Cinematic Phaser-based retro survival game.', description: 'A cinematic survival horror game with atmospheric storytelling, retro presentation, and reactive gameplay layers.', tags: ['Phaser', 'JavaScript', 'HTML5', 'Game Dev', 'Web Audio'], accent: 'purple', link: 'https://github.com/cser-utkarsh-raj/the-bloom', emoji: '🧟', status: 'under development', features: ['Narrative-driven survival gameplay', 'Atmospheric retro visuals and Web Audio', 'Layered world-building and event progression'] },
];

const accentMap = { lime: { color: '#a3e635', glow: 'rgba(163,230,53,0.16)' }, sky: { color: '#38bdf8', glow: 'rgba(56,189,248,0.16)' }, yellow: { color: '#fbbf24', glow: 'rgba(251,191,36,0.16)' }, rose: { color: '#fb7185', glow: 'rgba(251,113,133,0.16)' }, purple: { color: '#c084fc', glow: 'rgba(192,132,252,0.16)' } };

export default function Projects() {
  return (
    <section id="projects" className="section">
      <div className="container">
        <div className="reveal"><span className="section-label">selected work</span><h2 className="section-title">projects I'm proud of</h2><p className="section-subtitle">15+ apps built across full-stack development, AI, machine learning, developer tools, and games — with the 11 selected projects below.</p></div>
        <div className="projects-list">
          {projects.map((p, i) => { const a = accentMap[p.accent]; return (
            <article key={p.name} className="project-card reveal" style={{ '--accent': a.color, '--accent-glow': a.glow, transitionDelay: `${i * 80}ms` }}>
              <div className="project-card-glow" /><div className="project-head"><div className="project-emoji">{p.emoji}</div><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>{p.status && <span className="project-status">{p.status}</span>}<a className="project-link" href={p.link} target="_blank" rel="noopener noreferrer" aria-label={`View ${p.name} on GitHub`}><Github size={20} /></a></div></div>
              <h3 className="project-name">{p.name}</h3><p className="project-tagline">{p.tagline}</p>
              <div className="project-details"><div className="project-section"><span className="project-section-title">What it does</span><p className="project-desc">{p.description}</p></div><div className="project-section"><span className="project-section-title">Key highlights</span><ul className="project-features">{p.features.map((f) => <li key={f}><span className="project-bullet" style={{ background: a.color }} />{f}</li>)}</ul></div></div>
              <div className="project-tags">{p.tags.map((t) => <span key={t} className="project-tag">{t}</span>)}</div><a className="project-cta" href={p.link} target="_blank" rel="noopener noreferrer">View on GitHub <ArrowUpRight size={15} /></a>
            </article>
          ); })}
        </div>
      </div>
      <style>{`
        .projects-list { display:grid; grid-template-columns:repeat(2,1fr); gap:22px; }
        .project-card { position:relative; display:flex; flex-direction:column; padding:30px 28px 28px; border:1px solid var(--border); border-radius:20px; background:var(--bg-card); overflow:hidden; transition:transform .35s ease,border-color .35s ease; }
        .project-card:hover { transform:translateY(-6px); border-color:var(--accent); }
        .project-card-glow { position:absolute; top:-60px; right:-60px; width:180px; height:180px; border-radius:50%; background:var(--accent-glow); filter:blur(40px); opacity:0; transition:opacity .4s; }
        .project-card:hover .project-card-glow { opacity:1; }
        .project-head { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:24px; }
        .project-emoji { font-size:2rem; line-height:1; width:56px; height:56px; display:grid; place-items:center; border-radius:14px; background:rgba(255,255,255,.04); border:1px solid var(--border); }
        .project-link { color:var(--text-muted); padding:8px; border-radius:8px; transition:all .2s; }.project-link:hover { color:var(--accent); background:rgba(255,255,255,.04); }
        .project-status { font-family:var(--font-mono); font-size:.65rem; padding:3px 8px; border-radius:6px; background:rgba(192,132,252,.12); border:1px solid rgba(192,132,252,.3); color:#c084fc; text-transform:uppercase; letter-spacing:.05em; }
        .project-name { font-size:1.45rem; margin-bottom:8px; }.project-tagline { color:var(--accent); font-family:var(--font-mono); font-size:.82rem; margin-bottom:16px; line-height:1.5; }
        .project-details { display:flex; flex-direction:column; gap:20px; margin-bottom:24px; }.project-section { display:flex; flex-direction:column; gap:6px; }.project-section-title { font-family:var(--font-mono); font-size:.72rem; color:var(--accent); text-transform:uppercase; letter-spacing:.05em; opacity:.85; }.project-desc { color:var(--text-muted); font-size:.88rem; line-height:1.55; }
        .project-features { list-style:none; display:grid; gap:7px; }.project-features li { display:flex; align-items:flex-start; gap:10px; font-size:.84rem; color:var(--text-muted); line-height:1.45; }.project-bullet { width:5px; height:5px; border-radius:50%; flex-shrink:0; margin-top:6px; }
        .project-tags { display:flex; flex-wrap:wrap; gap:7px; margin-bottom:24px; }.project-tag { padding:4px 10px; border-radius:6px; background:rgba(255,255,255,.03); border:1px solid rgba(255,255,255,.06); font-size:.76rem; font-family:var(--font-mono); color:var(--text-dim); }.project-cta { margin-top:auto; display:inline-flex; align-items:center; gap:6px; font-weight:600; font-size:.92rem; color:var(--accent); transition:gap .2s; }.project-cta:hover { gap:10px; }
        @media (max-width:860px) { .projects-list { grid-template-columns:1fr; } }
      `}</style>
    </section>
  );
}
